spring:
  profiles:
    active: default

  datasource:
    url: jdbc:postgresql://localhost:5432/spring-boot-flyway
    username: demo
    password: demo

  sql:
    init:
      mode: always

  flyway:
    enabled: true
    locations: "classpath:db/migration,filesystem:/opt/migration"
#    schemas: public
#    url: jdbc:postgresql://localhost:5432/postgres
#    user: postgres
#    password: postgres

